### ISSUE TITLE
Unable to save scheduled time

### ISSUE THREAD

**Issue by 59n** [emerysilb/immibridge#1]
Hey nice project, seen it in reddit the other day and must say, very impressive, currently in the progress of uploading my gallery.

But I've ran into a issue where trying to set the schedule time at 08:00, upon restarting the app, it defaults back to 02:00, anyway to save it?

**Comment by emerysilb** [comment]
Thanks so much for trying it out! If I'm honest my Apple photos library hasn't fully synced so the scheduling may not be fully working, but yes I'll be sure to work on adding this!

**Comment by 59n** [comment]
Yes amazing so far, managed to upload 4k photos pretty fast but I've had to keep the parallel uploads stuck at 1, whenever I change it to a higher number the upload speeds would die down to a lower speed then if you just keep it at 1

**Comment by emerysilb** [comment]
Got it. Yeah the issue is that photokit only allows sequential requests so the parallel upload was mostly intended for if you have a local library and only need to bulk upload to immich, but I'm not 100% certain it works as I'd expect.

**Comment by 59n** [comment]
I see, no worries then, also, the new update you have pushed, I am unable to remove the app from my dock, whereas with the previous versions upon closing it, it would remain active in the menu bar but get removed from the dock, new feature or a bug? If its a feature, perhaps make it a setting you can change so users can switch between having it in the dock or not in the dock but menu bar when closed/minimized.

**Comment by emerysilb** [comment]
Good intel! Thanks for the quick feedback! I was trying to satisfy someone else that wanted it compatible with OSX version 12 and I thought that would only change the style of the app bar, but I guess it needs a bit more work. I'll take a look at it.

**Comment by emerysilb** [comment]
Just pushed a new build that should fix this 🤞

**Comment by 59n** [comment]
I've installed the new version, I am still unable to minimize it as it still remains in the dock, but the scheduled time now stays the same upon restarting the app, so that is fixed

**Comment by emerysilb** [comment]
You can also just close the window and it will keep working in the background.
